"""initial_create_all_tables

Revision ID: d2135e58fd8a
Revises: 
Create Date: 2026-06-11 09:26:01.657751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2135e58fd8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('file_role', sa.Enum('base', 'compare', name='file_role_enum'), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compare_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_no', sa.String(length=64), nullable=False),
    sa.Column('base_file_id', sa.Integer(), nullable=False),
    sa.Column('compare_file_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_file_id'], ['pdf_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['compare_file_id'], ['pdf_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_no')
    )
    op.create_table('pdf_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=1024), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['pdf_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pdf_pages_file_id', 'pdf_pages', ['file_id'], unique=False)
    op.create_table('page_regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('region_type', sa.String(length=128), nullable=False),
    sa.Column('region_name', sa.String(length=512), nullable=False),
    sa.Column('crop_image_path', sa.String(length=1024), nullable=True),
    sa.Column('bbox_json', sa.JSON(), nullable=False),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['pdf_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pdf_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_page_regions_file_id', 'page_regions', ['file_id'], unique=False)
    op.create_index('idx_page_regions_page_id', 'page_regions', ['page_id'], unique=False)
    op.create_table('ai_extraction_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('input_type', sa.Enum('full_page', 'region', 'merge', name='input_type_enum'), nullable=False),
    sa.Column('raw_output_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['pdf_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pdf_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['page_regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_extraction_runs_file_id', 'ai_extraction_runs', ['file_id'], unique=False)
    op.create_table('drawing_elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('extraction_run_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('element_name', sa.String(length=512), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.String(length=1024), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('importance', sa.Enum('high', 'medium', 'low', name='importance_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('need_manual_check', sa.Boolean(), nullable=False),
    sa.Column('source_image_path', sa.String(length=1024), nullable=True),
    sa.Column('region_desc', sa.Text(), nullable=True),
    sa.Column('extra_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['ai_extraction_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['pdf_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pdf_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['page_regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_drawing_elements_file_category', 'drawing_elements', ['file_id', 'category'], unique=False)
    op.create_index('idx_drawing_elements_file_id', 'drawing_elements', ['file_id'], unique=False)
    op.create_table('element_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('compare_task_id', sa.Integer(), nullable=False),
    sa.Column('base_element_id', sa.Integer(), nullable=True),
    sa.Column('compare_element_id', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.Enum('exact', 'semantic', 'suspicious', 'base_missing', 'compare_missing', name='match_type_enum'), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_element_id'], ['drawing_elements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['compare_element_id'], ['drawing_elements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['compare_task_id'], ['compare_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_element_matches_task_id', 'element_matches', ['compare_task_id'], unique=False)
    op.create_table('compare_diffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('compare_task_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('base_element_id', sa.Integer(), nullable=True),
    sa.Column('compare_element_id', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Enum('high', 'medium', 'low', 'manual_check', name='risk_level_enum'), nullable=False),
    sa.Column('diff_category', sa.String(length=128), nullable=False),
    sa.Column('base_content', sa.Text(), nullable=True),
    sa.Column('compare_content', sa.Text(), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('need_manual_check', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.Enum('pending', 'confirmed', 'ignored', 'misjudged', 'modified', name='review_status_enum'), nullable=False),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_element_id'], ['drawing_elements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['compare_element_id'], ['drawing_elements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['compare_task_id'], ['compare_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['element_matches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_compare_diffs_task_id', 'compare_diffs', ['compare_task_id'], unique=False)
    op.create_index('idx_compare_diffs_task_risk', 'compare_diffs', ['compare_task_id', 'risk_level'], unique=False)
    op.create_table('review_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('compare_diff_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('confirm', 'ignore', 'modify', 'mark_misjudged', name='review_action_enum'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compare_diff_id'], ['compare_diffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_logs_diff_id', 'review_logs', ['compare_diff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_review_logs_diff_id', table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index('idx_compare_diffs_task_risk', table_name='compare_diffs')
    op.drop_index('idx_compare_diffs_task_id', table_name='compare_diffs')
    op.drop_table('compare_diffs')
    op.drop_index('idx_element_matches_task_id', table_name='element_matches')
    op.drop_table('element_matches')
    op.drop_index('idx_drawing_elements_file_id', table_name='drawing_elements')
    op.drop_index('idx_drawing_elements_file_category', table_name='drawing_elements')
    op.drop_table('drawing_elements')
    op.drop_index('idx_ai_extraction_runs_file_id', table_name='ai_extraction_runs')
    op.drop_table('ai_extraction_runs')
    op.drop_index('idx_page_regions_page_id', table_name='page_regions')
    op.drop_index('idx_page_regions_file_id', table_name='page_regions')
    op.drop_table('page_regions')
    op.drop_index('idx_pdf_pages_file_id', table_name='pdf_pages')
    op.drop_table('pdf_pages')
    op.drop_table('compare_tasks')
    op.drop_table('pdf_files')
    # ### end Alembic commands ###
